# Generated by Django 4.2.16 on 2024-12-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_signtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contacttable',
        ),
        migrations.DeleteModel(
            name='signtable',
        ),
    ]
